

services:
  backend:
    image: backimg
    ports:
      - "3000:3000"
    env_file:
      - ./.env 
    restart: always
    networks:
      - back-teste
    volumes:
      - .:/usr/src/app

    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]
  
networks:
  back-teste:
    driver: bridge
